"""T0 契约清单，不注册可调用的业务路由。"""

from dataclasses import dataclass


@dataclass(frozen=True)
class Endpoint:
    method: str
    path: str
    name: str
    owner: str
    stage: str
    result: str | None
    request: str | None = None
    statuses: tuple[int, ...] = (200,)
    idempotent: bool = False
    versioned: bool = False
    anonymous: bool = False
    query: tuple[str, ...] = ()
    recovery: str | None = None
    persistence: str | None = None


ENDPOINTS = (
    Endpoint(
        "delete",
        "/room-bindings/{id}",
        "unbind_room",
        "room",
        "T3",
        "AcceptedOperation",
        statuses=(202,),
        idempotent=True,
        recovery="/operations/{id}",
        persistence="room.room_operations",
    ),
    Endpoint("get", "/room-bindings/{id}", "get_binding", "room", "T3", "Binding"),
    Endpoint("get", "/room-candidates/buildings", "list_buildings", "room", "T3", "FilterChoices"),
    Endpoint(
        "get",
        "/room-candidates/floors",
        "list_floors",
        "room",
        "T3",
        "FilterChoices",
        query=("building_id",),
    ),
    Endpoint(
        "get",
        "/room-candidates/rooms",
        "list_filtered_rooms",
        "room",
        "T3",
        "FilterChoices",
        query=("building_id", "floor"),
    ),
    Endpoint(
        "get", "/auth/agreement", "get_agreement", "identity", "T2", "Agreement", anonymous=True
    ),
    Endpoint(
        "post",
        "/auth/captcha",
        "create_captcha",
        "school_adapter",
        "T2",
        "Captcha",
        "CaptchaRequest",
        anonymous=True,
    ),
    Endpoint(
        "post",
        "/auth/login",
        "login",
        "identity",
        "T2",
        "LoginResult",
        "LoginRequest",
        anonymous=True,
    ),
    Endpoint("get", "/auth/me", "get_me", "identity", "T2", "Me"),
    Endpoint("post", "/auth/logout", "logout", "identity", "T2", None, statuses=(204,)),
    Endpoint(
        "delete",
        "/auth/school-credential",
        "revoke_credential",
        "identity",
        "T3",
        "AcceptedOperation",
        "VersionRequest",
        (202,),
        versioned=True,
        recovery="/operations/{id}",
        persistence="identity.credential_operations",
    ),
    Endpoint(
        "get", "/overview", "get_overview", "gateway", "T4", "Overview", query=("binding_id",)
    ),
    Endpoint(
        "get",
        "/room-bindings",
        "list_bindings",
        "room",
        "T2",
        "Bindings",
        query=("q", "page", "page_size"),
    ),
    Endpoint(
        "post",
        "/room-bindings/sync",
        "sync_bindings",
        "room",
        "T2",
        "AcceptedOperation",
        statuses=(202,),
        idempotent=True,
        recovery="/operations/{id}",
        persistence="room.room_operations",
    ),
    Endpoint(
        "get",
        "/room-candidates",
        "list_candidates",
        "room",
        "T2",
        "Candidates",
        query=("q", "page", "page_size", "room_id"),
    ),
    Endpoint(
        "post",
        "/room-bindings",
        "bind_room",
        "room",
        "T3",
        "AcceptedOperation",
        "BindRequest",
        (200, 202),
        idempotent=True,
        recovery="/operations/{id}",
        persistence="room.room_operations",
    ),
    Endpoint(
        "put",
        "/room-preferences/default",
        "set_default",
        "room",
        "T3",
        "AcceptedOperation",
        "DefaultRequest",
        (200, 202),
        versioned=True,
        recovery="/operations/{id}",
        persistence="room.room_operations",
    ),
    Endpoint("get", "/operations/{id}", "get_operation", "gateway", "T2", "Operation"),
    Endpoint("get", "/room-bindings/{id}/balance", "get_balance", "room", "T4", "Balance"),
    Endpoint(
        "post",
        "/room-bindings/{id}/balance-refresh",
        "refresh_balance",
        "room",
        "T4",
        "AcceptedOperation",
        statuses=(202,),
        idempotent=True,
        recovery="/operations/{id}",
        persistence="room.room_operations",
    ),
    Endpoint(
        "get",
        "/room-bindings/{id}/consumption",
        "get_consumption",
        "room",
        "T4",
        "Consumption",
        query=("start_date", "end_date", "granularity"),
    ),
    Endpoint(
        "post",
        "/room-bindings/{id}/history-sync",
        "sync_history",
        "room",
        "T4",
        "AcceptedOperation",
        "HistoryRequest",
        (202,),
        idempotent=True,
        recovery="/operations/{id}",
        persistence="room.history_syncs",
    ),
    Endpoint(
        "get",
        "/room-bindings/{id}/monitor-samples",
        "list_samples",
        "monitoring",
        "T4",
        "Samples",
        query=("start_date", "end_date", "page", "page_size", "snapshot_token"),
    ),
    Endpoint("get", "/monitor", "get_monitor", "monitoring", "T3", "Monitor"),
    Endpoint(
        "patch",
        "/monitor",
        "update_monitor",
        "monitoring",
        "T3",
        "Monitor",
        "MonitorPatch",
        versioned=True,
    ),
    Endpoint(
        "post",
        "/monitor/runs",
        "create_run",
        "monitoring",
        "T4",
        "AcceptedRun",
        statuses=(202,),
        idempotent=True,
        recovery="/monitor/runs/{id}",
        persistence="monitoring.monitor_runs",
    ),
    Endpoint("get", "/monitor/runs/{id}", "get_run", "monitoring", "T4", "Run"),
    Endpoint(
        "post",
        "/monitor/runs/{id}/cancel",
        "cancel_run",
        "monitoring",
        "T4",
        "Run",
        "VersionRequest",
        (200, 202),
        versioned=True,
        recovery="/monitor/runs/{id}",
        persistence="monitoring.monitor_runs",
    ),
    Endpoint(
        "get",
        "/payments/capabilities",
        "get_capabilities",
        "payment",
        "T6",
        "Capabilities",
        query=("binding_id",),
    ),
    Endpoint(
        "post",
        "/payment-orders",
        "create_order",
        "payment",
        "T6",
        "AcceptedOrder",
        "OrderRequest",
        (202,),
        idempotent=True,
        recovery="/payment-orders/{id}",
        persistence="payment.payment_orders",
    ),
    Endpoint("get", "/payment-orders/{id}", "get_order", "payment", "T6", "Order"),
    Endpoint(
        "get",
        "/payment-orders/{id}/qr",
        "get_qr",
        "payment",
        "T6",
        "QRPending",
        statuses=(200, 202),
        recovery="/payment-orders/{id}",
        persistence="payment.payment_operations",
    ),
    Endpoint(
        "post",
        "/payment-orders/{id}/qr-refresh",
        "refresh_qr",
        "payment",
        "T6",
        "AcceptedOperation",
        statuses=(202,),
        idempotent=True,
        recovery="/operations/{id}",
        persistence="payment.payment_operations",
    ),
)
