from enum import StrEnum


class ErrorCode(StrEnum):
    INVALID_ARGUMENT = "INVALID_ARGUMENT"
    INVALID_INTERVAL = "INVALID_INTERVAL"
    INVALID_DATE_RANGE = "INVALID_DATE_RANGE"
    CAPTCHA_INVALID = "CAPTCHA_INVALID"
    CAPTCHA_EXPIRED = "CAPTCHA_EXPIRED"
    APP_SESSION_EXPIRED = "APP_SESSION_EXPIRED"
    SCHOOL_LOGIN_REJECTED = "SCHOOL_LOGIN_REJECTED"
    CSRF_REJECTED = "CSRF_REJECTED"
    ORIGIN_REJECTED = "ORIGIN_REJECTED"
    NOT_FOUND = "NOT_FOUND"
    VERSION_CONFLICT = "VERSION_CONFLICT"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    OPERATION_IN_PROGRESS = "OPERATION_IN_PROGRESS"
    SCHOOL_REAUTH_REQUIRED = "SCHOOL_REAUTH_REQUIRED"
    REAUTH_ACCOUNT_MISMATCH = "REAUTH_ACCOUNT_MISMATCH"
    ROOM_CANDIDATE_EXPIRED = "ROOM_CANDIDATE_EXPIRED"
    SCHOOL_BINDING_REJECTED = "SCHOOL_BINDING_REJECTED"
    SNAPSHOT_EXPIRED = "SNAPSHOT_EXPIRED"
    SNAPSHOT_MISMATCH = "SNAPSHOT_MISMATCH"
    PRECONDITION_REQUIRED = "PRECONDITION_REQUIRED"
    RATE_LIMITED = "RATE_LIMITED"
    SCHOOL_PROTOCOL_CHANGED = "SCHOOL_PROTOCOL_CHANGED"
    SCHOOL_INVALID_RESPONSE = "SCHOOL_INVALID_RESPONSE"
    SCHOOL_UNAVAILABLE = "SCHOOL_UNAVAILABLE"
    CIRCUIT_OPEN = "CIRCUIT_OPEN"
    DEPENDENCY_UNAVAILABLE = "DEPENDENCY_UNAVAILABLE"
    SCHOOL_TIMEOUT = "SCHOOL_TIMEOUT"
    PAYMENT_UNAVAILABLE = "PAYMENT_UNAVAILABLE"
    FEATURE_DISABLED = "FEATURE_DISABLED"


HTTP_ERRORS = {
    400: [ErrorCode.CAPTCHA_INVALID, ErrorCode.CAPTCHA_EXPIRED, ErrorCode.SNAPSHOT_MISMATCH],
    401: [ErrorCode.APP_SESSION_EXPIRED, ErrorCode.SCHOOL_LOGIN_REJECTED],
    403: [
        ErrorCode.CSRF_REJECTED,
        ErrorCode.ORIGIN_REJECTED,
        ErrorCode.PAYMENT_UNAVAILABLE,
        ErrorCode.FEATURE_DISABLED,
    ],
    404: [ErrorCode.NOT_FOUND],
    409: [
        ErrorCode.VERSION_CONFLICT,
        ErrorCode.IDEMPOTENCY_CONFLICT,
        ErrorCode.OPERATION_IN_PROGRESS,
        ErrorCode.SCHOOL_REAUTH_REQUIRED,
        ErrorCode.REAUTH_ACCOUNT_MISMATCH,
    ],
    410: [ErrorCode.ROOM_CANDIDATE_EXPIRED, ErrorCode.SNAPSHOT_EXPIRED],
    422: [ErrorCode.INVALID_ARGUMENT, ErrorCode.INVALID_INTERVAL, ErrorCode.INVALID_DATE_RANGE],
    428: [ErrorCode.PRECONDITION_REQUIRED],
    429: [ErrorCode.RATE_LIMITED],
    502: [ErrorCode.SCHOOL_PROTOCOL_CHANGED, ErrorCode.SCHOOL_INVALID_RESPONSE],
    503: [ErrorCode.SCHOOL_UNAVAILABLE, ErrorCode.CIRCUIT_OPEN, ErrorCode.DEPENDENCY_UNAVAILABLE],
    504: [ErrorCode.SCHOOL_TIMEOUT],
}
